### PR TITLE
Update active-directory-whatis.md

### PR DESCRIPTION
**Pull request by andygonusa**
Added additional resources for this topic - Spanish How to or Azure

### CODE REVIEW

**Comment by gosali** [comment]
Hi @andygonusa, we are still in discussing, will update the decision later soon. 
		
Thanks for your support,
Microsoft C&E Localization Team

**Comment by andygonusa** [comment]
Hi Team, any updates on this?

**Comment by gosali** [comment]
Hi @andygonusa, we are still in discussing, will update the decision later soon.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @andygonusa, we are still in discussing, will update the decision later soon.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@andygonusa Thank you for your feedback and suggestion! 
		
We found that the link in yor feedback does not belong to an existing article, which is not fully aligned to our acceptance criterial, I am closing this PR. 
		
Microsoft C&E Localization Team

**Pull request closed without merging**
